Gera::CurrencyRatesWorker:
  cron: '*/15 * * * *'
  class: Gera::CurrencyRatesWorker
  queue: default

Gera::DirectionsRatesWorker:
  cron: '3 * * * *'
  class: Gera::DirectionsRatesWorker
  queue: critical

Gera::PurgeCurrencyRatesWorker:
  cron: '27 2 * * *'
  class: Gera::PurgeCurrencyRatesWorker
  queue: purgers

Gera::PurgeDirectionRatesWorker:
  cron: '27 3 * * *'
  class: Gera::PurgeDirectionRatesWorker
  queue: purgers

Gera::CreateHistoryIntervalsWorker:
  cron: '*/17 * * * *'
  class: Gera::CreateHistoryIntervalsWorker
  queue: default


### Gera: Import external rates
#
#
Gera::CBRRatesWorker:
  cron: '30 * * * *'
  class: Gera::CBRRatesWorker
  queue: critical

# https://support.exmoney.com/hc/ru/articles/360013113933-%D0%94%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D0%BE%D0%B5-%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE-%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2%D0%BE%D0%B2-API
Gera::EXMORatesWorker:
  cron: '*/1 * * * *'
  class: Gera::EXMORatesWorker
  queue: critical


# API limits: 30 rpm
#
Gera::BitfinexRatesWorker:
  cron: '*/1 * * * *'
  class: Gera::BitfinexRatesWorker
  queue: critical
